### ISSUE TITLE
Does this plugin support the autocomplete.php format definition?

### ISSUE THREAD

**Issue by tiansin** [felixfbecker/vscode-php-intellisense#145] opened 2017-08-15 15:21 UTC
I use the codeignite3.15 framework, $ this-> uri & $ this-> db & $ this-> session ... ..., this does not support intellisense.

----
this autocomplete.php format.
* @property CI_DB_active_record $db              This is the platform-independent base Active Record implementation class.
* @property CI_DB_forge $dbforge                 Database Utility Class
* @property CI_Benchmark $benchmark              This class enables you to mark points and calculate the time difference between them.<br />  Memory consumption can also be displayed.
* @property CI_Calendar $calendar                This class enables the creation of calendars
* @property CI_Cart $cart                        Shopping Cart Class
* @property CI_Config $config                    This class contains functions that enable config files to be managed
.....

**Comment by felixfbecker** [comment] 2017-08-15 15:46
Duplicate of https://github.com/felixfbecker/php-language-server/issues/458
You can use `@var` for your properties.

**Closed by felixfbecker** 2017-08-15 15:46 UTC

**Comment by Zolcsi67** [comment] 2018-01-05 12:14
@felixfbecker could you write an example? I tried the following:

```php
/**
 * @var Db $db
 */
```

```php
/**
 * @property $db
 * @var Db
 */
```

None of them worked. This is what my magic getter function looks like:
```php

    public function __get($property)
    {
        switch($property)
        {
            case 'db':
                return Db::Load();
        }
        return null;
    }
```

**Comment by jens1o** [comment] 2018-01-05 12:14
Magic getters aren't supported, yet.

**Comment by pedroresende** [comment] 2018-06-12 14:07
@jens1o Any news about this feature ?

**Comment by jens1o** [comment] 2018-06-12 18:20
@pedroresende no.
