### ISSUE TITLE
Format Document does not honor indentation using tabs

### ISSUE THREAD

**Issue by morganwdavis** [felixfbecker/vscode-php-intellisense#175] opened 2017-11-08 19:51 UTC
With this extension, Format Document rebuilds the whole source file using fixed 4-character spaces, replacing tabs if that is the VSCode preferred settings.

**Comment by jens1o** [comment] 2017-11-08 19:53
Ehm. Format Document will be removed with the next version, because of the reason you provided(and others)

See https://github.com/felixfbecker/php-language-server/issues/501

**Comment by felixfbecker** [comment] 2017-11-08 19:54
Also a duplicate of https://github.com/felixfbecker/php-language-server/issues/343

**Closed by felixfbecker** 2017-11-08 19:54 UTC

**Comment by morganwdavis** [comment] 2017-11-08 20:19
Oh... sorry.  And cool.  Is there a recommended alternative extension to get "Format Document" support for PHP?

**Comment by felixfbecker** [comment] 2017-11-08 20:20
phpcs will give you the exact same formatting this extension had.
