### ISSUE TITLE
PHP's built-in function docblocks not showing up

### ISSUE THREAD

**Issue by gopi-ar** [felixfbecker/vscode-php-intellisense#171] opened 2017-11-02 13:19 UTC
For any built-in PHP function, there are no suggestions beyond the function name. For e.g., typing `explode` just shows `explode()` but not the expected params like `($delimeter, $array)` the default PHP suggestion plugin in vscode.

At the moment I'm having to leave the default vscode `"php.suggest.basic"` as `true` so I can see this behaviour.

Is this expected or a misconfig on my end?

**Comment by felixfbecker** [comment] 2017-11-02 17:00
Duplicate of https://github.com/felixfbecker/php-language-server/issues/18

**Closed by felixfbecker** 2017-11-02 17:00 UTC
