### ISSUE TITLE
Exclude paths from validation

### ISSUE THREAD

**Issue by Zebradil** [felixfbecker/vscode-php-intellisense#217] opened 2017-12-02 21:38 UTC
Hi there!
Thanks for your work and for this useful extension!

I wonder to know if there is a way to exclude particular paths from validation. For example, I don't need to validate Symfony cache folder — there are a lot of spamming messages with which I can do nothing.

**Comment by felixfbecker** [comment] 2017-12-02 21:48
Duplicate of https://github.com/felixfbecker/php-language-server/issues/159

**Closed by felixfbecker** 2017-12-02 21:48 UTC
