### ISSUE TITLE
[ASK] PHP Intellisense - Parameters Explanation

### ISSUE THREAD

**Issue by benyaminl** [felixfbecker/vscode-php-intellisense#191] opened 2017-11-15 11:36 UTC
Hello, I want to ask about VS Code Interllisense Explanation, is there anyway to make Php Intellisense to read php doc block about what parameters is available and what's that parameter used? Thanks...
(I use IntepHENSE for sometimes, but for now I go back with your extension. Is there anyway arround? Thanks)

**Comment by felixfbecker** [comment] 2017-11-15 18:29
This is a duplicate of https://github.com/felixfbecker/php-language-server/issues/18 and there is an open PR if you want to take that over the finish line.

**Closed by felixfbecker** 2017-11-15 18:29 UTC
