### ISSUE TITLE
Auto complete funcionality takes several seconds to appear

### ISSUE THREAD

**Issue by mfgabriel92** [felixfbecker/vscode-php-intellisense#368] opened 2018-09-26 03:19 UTC
I'm using the Visual Studio Code version 1.27.2, and it takes 5 seconds or more for the suggestion pop-up to pop and suggest a code completion. Without the extension it is fast. Pressing ctrl + space makes it show up, but with a "Loading..." message instead that will also take 5 seconds or more to display the suggestions.

**Comment by oojacoboo** [comment] 2018-09-27 17:37
Several seconds is generous.  I have a new Macbook Pro and sometimes it takes nearly 10 seconds.  Also, other times, it flat out doesn't work.

I've found the PHP INtelephense plugin with VSCode to be much much faster and more reliable.  I'm not sure it's as full featured, but this plugin is basically worthless for us.  Maybe it's better with small projects, I can't say.

**Comment by felixfbecker** [comment] 2018-09-27 17:39
Duplicate of https://github.com/felixfbecker/php-language-server/issues/274

**Closed by felixfbecker** 2018-09-27 17:39 UTC

**Comment by mfgabriel92** [comment] 2018-09-28 04:00
@oojacoboo, indeed, PHP Intelephense seems to be much faster.
@felixfbecker, thank you.
