### ISSUE TITLE
Check directory permissions

### ISSUE THREAD

**Issue by bweston92** [felixfbecker/vscode-php-intellisense#132] opened 2017-07-12 09:53 UTC
Don't fail when scanning directories that the process doesn't have permission to, just skip them.

For example this makes Intellisense not work at all.
```
UnexpectedValueException: RecursiveDirectoryIterator::construct(/home/bweston/workspace/src/legalweb.tech/cosmicapp/cosmicapp.co.uk/.persistent/mysql/sys): failed to open dir: Permission denied in /home/bweston/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php:43
```

**Comment by nyon** [comment] 2017-07-21 07:03
I have the same problem. A good solution would be to exclude all directories that are also excluded by visual studio code (files.exclude).

**Comment by aciobanu** [comment] 2017-08-09 17:31
+1

**Comment by felixfbecker** [comment] 2017-10-29 22:17
Duplicate of https://github.com/felixfbecker/php-language-server/issues/462

**Closed by felixfbecker** 2017-10-29 22:17 UTC
