### ISSUE TITLE
no completion for try

### ISSUE THREAD

**Issue by yangweijie** [felixfbecker/vscode-php-intellisense#140] opened 2017-07-30 03:49 UTC
i see foreach  is able to complet to 
```
foreach ($variable as $key => $value) {
 code...
}
```
but not see try

**Comment by felixfbecker** [comment] 2017-10-29 22:15
duplicate of https://github.com/felixfbecker/php-language-server/issues/200

**Closed by felixfbecker** 2017-10-29 22:15 UTC
