### ISSUE TITLE
html in php file - enter after html tag always choses autocomplete

### ISSUE THREAD

**Issue by ingageco** [felixfbecker/vscode-php-intellisense#138] opened 2017-07-29 14:49 UTC
Writing HTML inside a PHP document causes <?php to be suggested immediately after finishing a HTML tag. Definitely annoying if you consistently want to enter down after writing an HTML line. Any suggestions on how i can fix? Thanks for the help. 

![screen shot 2017-07-28 at 1 32 51 pm](https://user-images.githubusercontent.com/1514415/28745698-866c2300-744b-11e7-80ac-e8f93932543e.png)

**Comment by felixfbecker** [comment] 2017-07-29 16:53
Duplicate of https://github.com/felixfbecker/php-language-server/issues/372

**Closed by felixfbecker** 2017-07-29 16:53 UTC
