### ISSUE TITLE
Config to choose file extensions

### ISSUE THREAD

**Issue by neerolyte** [felixfbecker/vscode-php-intellisense#142] opened 2017-08-07 00:03 UTC
I think this actually belongs here, sorry if I'm wrong!

There's no obvious config options to tell the intellisense extension to include other file extensions as if they are PHP files.

I have extra extensions in `files.associations` already configured, but intellisense doesn't seem to pick them up.

**Comment by zairig** [comment] 2018-01-24 18:44
Hello @neerolyte,
I have the same issue with .module files not being indexed (Drupal projects). This is the only thing which blocks me from switching to VSCode. Did you find a solution to this bug?

**Comment by neerolyte** [comment] 2018-01-24 21:10
I'm using https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client instead, it's significantly less populate, has its own annoying set of bugs, but at least picks up files configured as php in the `file.associations` config key.

**Comment by felixfbecker** [comment] 2018-01-24 21:14
Duplicate of https://github.com/felixfbecker/php-language-server/issues/300

**Closed by felixfbecker** 2018-01-24 21:14 UTC
