### ISSUE TITLE
auto completion fail in global variable 

### ISSUE THREAD

**Issue by chengte99** [felixfbecker/vscode-php-intellisense#365] opened 2018-09-12 07:58 UTC
![global](https://user-images.githubusercontent.com/28803537/45410157-a640f700-b6a3-11e8-8e37-20e2237675bf.png)
![normal](https://user-images.githubusercontent.com/28803537/45410164-a80aba80-b6a3-11e8-8e85-bad4f61245f5.png)
![config](https://user-images.githubusercontent.com/28803537/45410238-cffa1e00-b6a3-11e8-96f8-1974cdfa5f89.png)
I'm a PHP beginer, I have some question.
When I use global variable, the method didn't show auto completion, but normal variable is work.
Do I miss some configuration? or it's unsupported?
Anyone can help me? thanks

**Comment by felixfbecker** [comment] 2018-09-12 09:17
That’s not a global variable, that’s a class property. You need to annotate it with a /** @var TYPE */ comment or the languagse server has no way to know its type. If you need more help please ask on StackOverflow/Gitter. Closing as this is not a bug.

**Closed by felixfbecker** 2018-09-12 09:17 UTC
