### ISSUE TITLE
PHP Scanning File in VS Code

### ISSUE THREAD

**Issue by faithfulman18** [felixfbecker/vscode-php-intellisense#403] opened 2018-12-12 01:57 UTC
When I open VS Code and it's a project that has files that have PHP in them, it seems to automatically scan through the files and detect syntax errors sometimes.  However, I specifically am noticing that any of the files that have a "*.html" extension don't get automatically scanned until I manually open them.

Would there be a way to tell your plugin to scan other files than just the ones with the .php extension?

**Comment by benyaminl** [comment] 2019-04-01 02:17
Why we need html file to be indexed?

**Comment by felixfbecker** [comment] 2019-04-01 12:48
Duplicate of https://github.com/felixfbecker/php-language-server/issues/300

**Closed by felixfbecker** 2019-04-01 12:48 UTC
