### ISSUE TITLE
settings for faster autocomplete suggestion?

### ISSUE THREAD

**Issue by icenold** [felixfbecker/vscode-php-intellisense#155] opened 2017-09-28 18:37 UTC
every time I type a letter it takes like 1.5 seconds for the suggestions to show

OS: Linux mint - Sonya
Mem: 8gb
vscode version: 1.16.1
extension version: latest as of sept 9, 2017

**Comment by str** [comment] 2017-10-02 16:50
My intellisense also takes way to long to show the drop down list to select an option.

**Comment by felixfbecker** [comment] 2017-10-29 22:29
Duplicate of https://github.com/felixfbecker/php-language-server/issues/274

**Closed by felixfbecker** 2017-10-29 22:29 UTC

**Comment by pilishen** [comment] 2018-07-20 08:22
@felixfbecker just mark a duplicate and close this doesn't help anything
