### ISSUE TITLE
Use VScode's indent setting for formatting code

### ISSUE THREAD

**Issue by erbesharat** [felixfbecker/vscode-php-intellisense#153] opened 2017-09-25 19:18 UTC
Whenever I use format code option it uses 4 spaces tab size but I've set my VScode settings to 2 spaces.
It would be great if this extension used VScode's setting instead of its default settings.

**Comment by felixfbecker** [comment] 2017-11-08 19:55
Duplicate of https://github.com/felixfbecker/php-language-server/issues/343

**Closed by felixfbecker** 2017-11-08 19:55 UTC
