### ISSUE TITLE
Memory leak on php7.1 process

### ISSUE THREAD

**Issue by cpxPratik** [felixfbecker/vscode-php-intellisense#236] opened 2017-12-29 10:07 UTC
On ubuntu16.04, with PHP version 7.1 with vscode version: 1.19.1, PHP Intellisense extension version: 2.2.2 :

When opening php-related projects, process named php7.1 takes up all the memory(I had to do `sudo killall -9 php7.1` immediately on console) and Ubuntu basically freezes. Tried with this extension uninstalled, then the problem does not appear while re-appears after installing this extension.

While opening simple project such as minimal symfony bundle, memory leak doesn't happen(process named `php7.1` stays on 292MB memory). But complex project than that makes the process take memory exponentially within few seconds.

**Comment by felixfbecker** [comment] 2017-12-30 01:35
Duplicate of #192

**Closed by felixfbecker** 2017-12-30 01:35 UTC
