### ISSUE TITLE
The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by gitscofield** [felixfbecker/vscode-php-intellisense#237] opened 2017-12-30 00:59 UTC
errror for thinkphp5.0   in vscode .

[Info  - 08:30:48] 1147 files total
[Info  - 08:30:48] Indexing project for definitions and static references
[Error - 08:32:24] Connection to server got closed. Server will not be restarted.

**Comment by felixfbecker** [comment] 2017-12-30 01:00
Could you please check the console (Help > Toggle Development Tools)

**Comment by gitscofield** [comment] 2017-12-30 01:33
**This is a new version of the error, and the previous version did not.
I was updated in December 18th**

**The console info:**


[Extension Host] debugger listening on port 9335
workbench.main.js:sourcemap:2569 [Extension Host] debugger inspector at %cDebugger listening on port 9335.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9335/a11a4d78-97a2-43f5-9f4c-45112a3ae2f6

workbench.main.js:sourcemap:249 [Extension Host] Crane Initialised...
workbench.main.js:sourcemap:249 [Extension Host] PHP process connected
workbench.main.js:sourcemap:249 [Extension Host] 
Fatal error: Out of memory (allocated 1803550720) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 1123

workbench.main.js:sourcemap:249 [Extension Host] PHP process disconnected
workbench.main.js:sourcemap:249 [Extension Host] 
VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��


VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��

PHP Fatal error:  Out of memory (allocated 1803550720) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 1123

t.log @ workbench.main.js:sourcemap:249
workbench.main.js:sourcemap:249 [Extension Host] PHP process connected
workbench.main.js:sourcemap:249 [Extension Host] 
Fatal error: Out of memory (allocated 1805647872) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 1123

workbench.main.js:sourcemap:249 [Extension Host] PHP process disconnected
workbench.main.js:sourcemap:249 [Extension Host] 
VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��


VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��

PHP Fatal error:  Out of memory (allocated 1805647872) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 1123

t.log @ workbench.main.js:sourcemap:249
workbench.main.js:sourcemap:249 [Extension Host] PHP process connected
workbench.main.js:sourcemap:249 [Extension Host] 
Fatal error: Out of memory (allocated 1807745024) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 710

workbench.main.js:sourcemap:249 [Extension Host] PHP process disconnected
workbench.main.js:sourcemap:249 [Extension Host] 
VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��


VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��

PHP Fatal error:  Out of memory (allocated 1807745024) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 710

t.log @ workbench.main.js:sourcemap:249
workbench.main.js:sourcemap:249 [Extension Host] PHP process connected
workbench.main.js:sourcemap:249 [Extension Host] 
Fatal error: Out of memory (allocated 1803550720) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 710

workbench.main.js:sourcemap:249 [Extension Host] PHP process disconnected
workbench.main.js:sourcemap:249 [Extension Host] 
VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��


VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��

PHP Fatal error:  Out of memory (allocated 1803550720) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 710

t.log @ workbench.main.js:sourcemap:249
workbench.main.js:sourcemap:249 [Extension Host] PHP process connected
workbench.main.js:sourcemap:249 [Extension Host] 
Fatal error: Out of memory (allocated 1805647872) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 1123

workbench.main.js:sourcemap:249 [Extension Host] PHP process disconnected
workbench.main.js:sourcemap:249 [Extension Host] 
VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��


VirtualAlloc() failed: [0x00000008] �洢�ռ䲻�㣬�޷���������


VirtualFree() failed: [0x000001e7] ��ͼ������Ч�ĵ�ַ��

PHP Fatal error:  Out of memory (allocated 1805647872) (tried to allocate 262144 bytes) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 1123

t.log @ workbench.main.js:sourcemap:249
workbench.main.js:sourcemap:2744 The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by felixfbecker** [comment] 2017-12-30 01:34
Duplicate of #236

**Closed by felixfbecker** 2017-12-30 01:34 UTC
Labels: needs more info
